#!/usr/bin/env node
/*jslint node: true */
"use strict";

var fs = require("fs"),
    lexer = require("../source/lexer"),
    parser = require("../source/parser"),
    filename = process.argv[2],
    code = fs.readFileSync(filename, "utf8"),
    ast = parser.parse(lexer.tokenize(code));

console.log(JSON.stringify(ast));
