#!/usr/bin/env node

/*jslint node: true */
"use strict";

var readline = require("readline"),
    colors = require("colors"),
    rl = readline.createInterface(process.stdin, process.stdout),
    lexer = require("../source/lexer"),
    parser = require("../source/parser"),
    interpreter = require("../source/interpreter");

rl.setPrompt("> ");
rl.prompt();

rl.on("line", function (line) {
    var result = String(interpreter.evaluate(
        parser.parse(
            lexer.tokenize(
                line,
                { verbose: true }
            ),
            { verbose: true }
        )
    ));

    console.log(result.grey);
    rl.prompt();
}).on("close", function () {
    console.log("Bye bye.".yellow);
    process.exit(0);
});
